CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE user_table (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    password CITEXT NOT NULL,
    gender CHAR(1) NOT NULL CHECK (IN ('M', 'F', 'O')),
    email VARCHAR(255) NOT NULL
);